# Generated by Django 2.0.2 on 2018-03-20 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzina', models.CharField(choices=[('rodzina1', 'rodzina1'), ('rodzina2', 'rodzina12')], max_length=1)),
                ('chronione', models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], max_length=1)),
                ('endemity', models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='static/galeria/rosliny')),
            ],
        ),
        migrations.CreateModel(
            name='Roslina',
            fields=[
                ('id_rosliny', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_polska', models.CharField(max_length=256)),
                ('nazwa_lacinska', models.CharField(max_length=256)),
                ('opis', models.TextField()),
                ('data', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='nazwa_polska',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='basic_app.Roslina'),
        ),
        migrations.AddField(
            model_name='cecha',
            name='nazwa_polska',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cecha', to='basic_app.Roslina'),
        ),
    ]
