# Generated by Django 2.0.2 on 2018-03-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cecha',
            name='chronione',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], max_length=5),
        ),
        migrations.AlterField(
            model_name='cecha',
            name='endemity',
            field=models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], max_length=5),
        ),
        migrations.AlterField(
            model_name='cecha',
            name='rodzina',
            field=models.CharField(choices=[('rodzina1', 'rodzina1'), ('rodzina2', 'rodzina12')], max_length=100),
        ),
    ]
