# Generated by Django 2.0.2 on 2018-03-20 14:03

import basic_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20180320_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(max_length=255, upload_to=basic_app.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='images',
            name='nazwa_polska',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='basic_app.Roslina'),
        ),
    ]
