# Generated by Django 2.0.2 on 2018-03-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20180322_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='krotkiOpis',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='roslina',
            name='chronione',
            field=models.CharField(blank=True, choices=[('y', 'Tak'), ('n', 'Nie')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='roslina',
            name='czerwona_księga',
            field=models.CharField(blank=True, choices=[('y', 'Tak'), ('n', 'Nie')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='roslina',
            name='endemity',
            field=models.CharField(blank=True, choices=[('y', 'Tak'), ('n', 'Nie')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='roslina',
            name='kategoria',
            field=models.CharField(blank=True, choices=[('pap', 'Paprotniki'), ('drz', 'Drzewa Krzewy Krzewinki'), ('tra', 'Turzycowate Trawy'), ('bia', 'Zielne - Kwiaty białe'), ('zol', 'Zielne - Kwiaty żółte'), ('cze', 'Zielne - Kwiaty czerwone')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='roslina',
            name='kolor_kwiatow',
            field=models.CharField(blank=True, choices=[('bb', 'bezbarwny'), ('bi', 'biały'), ('br', 'brązowy'), ('cz', 'czerwony'), ('fi', 'fioletowy'), ('nb', 'niebieski'), ('po', 'pomarańczowy'), ('ro', 'różowy'), ('gr', 'zielony'), ('zo', 'żółty')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='roslina',
            name='lecznicze',
            field=models.CharField(blank=True, choices=[('y', 'Tak'), ('n', 'Nie')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='roslina',
            name='owadozerne',
            field=models.CharField(blank=True, choices=[('y', 'Tak'), ('n', 'Nie')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='roslina',
            name='pasozytnicze',
            field=models.CharField(blank=True, choices=[('y', 'Tak'), ('n', 'Nie')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='roslina',
            name='pietro_roslinnosci',
            field=models.CharField(blank=True, choices=[('pog', 'Piętro pogórza'), ('dol', 'Piętro regla dolnego'), ('gor', 'Piętro regla górnego'), ('kos', 'Piętro kosodrzewiny'), ('hal', 'Piętro halne'), ('tur', 'Piętro turniowe'), ('pol', 'Piętro połonin (Bieszczady)')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='roslina',
            name='rodzina',
            field=models.CharField(blank=True, choices=[('Agres', 'Agrestowate'), ('Amary', 'Amarylkowate'), ('Arali', 'Araliowate'), ('Astro', 'Astrowate (Złożone)'), ('Babko', 'Babkowate'), ('Bagni', 'Bagnicowate'), ('Balda', 'Baldaszkowate (Selerowate)'), ('Bazyn', 'Bażynowate'), ('Berbe', 'Berberysowate'), ('Bobow', 'Bobowate (Motylkowate)'), ('Bobrk', 'Bobrkowate'), ('Bodzi', 'Bodziszkowate'), ('Brzoz', 'Brzozowate'), ('Bukow', 'Bukowate'), ('Cisow', 'Cisowate'), ('Cypry', 'Cyprysowate'), ('Czyst', 'Czystkowate (Posłonkowate)'), ('Deren', 'Dereniowate'), ('Dynio', 'Dyniowate'), ('Dziew', 'Dziewięciornikowate'), ('Dziur', 'Dziurawcowate'), ('Dzwon', 'Dzwonkowate'), ('Fiolk', 'Fiołkowate'), ('Gazew', 'Gązewnikowate'), ('Goryc', 'Goryczkowate'), ('Gozdz', 'Goździkowate'), ('Grubo', 'Gruboszowate'), ('Grusz', 'Gruszyczkowate'), ('Grzyb', 'Grzybieniowate'), ('Jaskr', 'Jaskrowate'), ('Jasno', 'Jasnotowate (Wargowe)'), ('Jezog', 'Jeżogłowkowate'), ('Kania', 'Kaniankowate'), ('Kapus', 'Kapustowate(Krzyżowe)'), ('Kaszt', 'Kasztanowcowate'), ('Klono', 'Klonowate'), ('Kloko', 'Kłokoczkowate'), ('Kokor', 'Kokornakowate'), ('Komos', 'Komosowate'), ('Konop', 'Konopiowate'), ('Kosac', 'Kosaćcowate'), ('Kozlk', 'Kozłkowate'), ('Krwaw', 'Krwawnicowate'), ('Krzyz', 'Krzyżowe(Kapustowate)'), ('Krzyp', 'Krzyżownicowate'), ('Leszc', 'Leszczynowate'), ('Lilio', 'Liliowate'), ('Lipow', 'Lipowate'), ('Lnowa', 'Lnowate'), ('Laczn', 'Łączniowate'), ('Makow', 'Makowate'), ('Marza', 'Marzanowate'), ('Motyl', 'Motylkowate(Bobowate)'), ('Nasie', 'Nasiężrzałowate'), ('Nieci', 'Niecierpkowate'), ('Obraz', 'Obrazkowate'), ('Ogore', 'Ogórecznikowate'), ('Oliwk', 'Oliwkowate'), ('Orlic', 'Orlicowate'), ('Tamar', 'Tamaryszkowate'), ('Toino', 'Toinowate'), ('Trawy', 'Trawy (Wiechlinowate)'), ('Tredo', 'Trędownikowate'), ('Troje', 'Trojeściowate'), ('Trzmi', 'Trzmielinowate'), ('Turzy', 'Turzycowate'), ('Wargo', 'Wargowe (Jasnotowate)'), ('Wawrz', 'Wawrzynkowate'), ('Werbe', 'Werbenowate'), ('Wiazo', 'Wiązowate'), ('Widli', 'Widliczkowate'), ('Widla', 'Widłakowate'), ('Wiech', 'Wiechlinowate (Trawy)'), ('Wielo', 'Wielosiłowate'), ('Wierz', 'Wierzbowate'), ('Wiesi', 'Wiesiołkowate'), ('Wietl', 'Wietlicowate'), ('Wilcz', 'Wilczomleczowate'), ('Winor', 'Winoroślowate'), ('Wodni', 'Wodnikowate'), ('Wrzos', 'Wrzosowate'), ('Zachy', 'Zachylnikowate'), ('Zanok', 'Zanokcicowate'), ('Zaraz', 'Zarazowate'), ('Zlozo', 'Złożone (Astrowate)'), ('Zabie', 'Żabieńcowate'), ('Zabis', 'Żabiściekowate'), ('Palko', 'Pałkowate'), ('Papro', 'Paprotkowate'), ('Papre', 'Paprotnikowate'), ('Pierw', 'Pierwiosnkowate'), ('Pizma', 'Piżmaczkowate'), ('Plywa', 'Pływaczowate'), ('Podrz', 'Podrzeniowate'), ('Pokrz', 'Pokrzywowate'), ('Poryb', 'Poryblinowate'), ('Poslo', 'Posłonkowate (Czystkowate)'), ('Powoj', 'Powojowate'), ('Przew', 'Przewiertniowate'), ('Przes', 'Przęstkowate'), ('Psian', 'Psiankowate'), ('Rdest', 'Rdestnicowate'), ('Rdest', 'Rdestowate'), ('Rezed', 'Rezedowate'), ('Rokit', 'Rokitnikowate'), ('Rosic', 'Rosiczkowate'), ('Rozow', 'Różowate'), ('Rzeso', 'Rzęsowate'), ('Rzesl', 'Rzęślowate'), ('Sanda', 'Sandałowcowate'), ('Seler', 'Selerowate (Baldaszkowe)'), ('Sitow', 'Sitowate'), ('Skaln', 'Skalnicowate'), ('Skrzy', 'Skrzypowate'), ('Sosno', 'Sosnowate'), ('Storc', 'Storczykowate'), ('Szakl', 'Szakłakowate'), ('Szarl', 'Szarłatowate'), ('Szcza', 'Szczawikowate'), ('Szcze', 'Szczeciowate'), ('Szors', 'Szorstkolistne'), ('Slazo', 'Ślazowate'), ('Swibk', 'Świbkowate')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='roslina',
            name='trujace',
            field=models.CharField(blank=True, choices=[('y', 'Tak'), ('n', 'Nie')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='roslina',
            name='wystepowanie',
            field=models.TextField(blank=True, null=True),
        ),
    ]
