# Generated by Django 2.0.2 on 2018-03-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20180322_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roslina',
            name='chronione',
            field=models.CharField(blank=True, choices=[('y', 'Tak'), ('n', 'Nie')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='roslina',
            name='czerwona_księga',
            field=models.CharField(blank=True, choices=[('y', 'Tak'), ('n', 'Nie')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='roslina',
            name='endemity',
            field=models.CharField(blank=True, choices=[('y', 'Tak'), ('n', 'Nie')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='roslina',
            name='lecznicze',
            field=models.CharField(blank=True, choices=[('y', 'Tak'), ('n', 'Nie')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='roslina',
            name='owadozerne',
            field=models.CharField(blank=True, choices=[('y', 'Tak'), ('n', 'Nie')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='roslina',
            name='pasozytnicze',
            field=models.CharField(blank=True, choices=[('y', 'Tak'), ('n', 'Nie')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='roslina',
            name='trujace',
            field=models.CharField(blank=True, choices=[('y', 'Tak'), ('n', 'Nie')], default='n', max_length=1),
        ),
    ]
