# Generated by Django 2.0.2 on 2018-03-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20180322_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='krotkiOpis',
        ),
        migrations.AddField(
            model_name='images',
            name='zdjecie_glowne',
            field=models.CharField(choices=[('y', 'Tak'), ('n', 'Nie')], default='n', max_length=1),
        ),
    ]
